version: '3.8'

services:
  web:
    build: .
    container_name: youtube_downloader
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
