version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selenium_agent_manager_on_web
    restart: always
    volumes:
      - .:/app
    ports:
      - "8030:8030"
    

